### ISSUE TITLE
Add readme 

### ISSUE THREAD

**Issue by hadley** [metacran/metacranweb#62]
With instructions on how to run locally

**Comment by gaborcsardi** [comment]
Yes, not included, because it is standard node.js.
But it is easy. Install node.js first, a recent version. Then

```
npm install
PORT=3001 bin/www
```

Then go to http://localhost:3001 in your browser. Almost everything works, but the READMEs and NEWS files are served from a private db, so those will be missing. I'll need to make that DB public first.

Also, you might want to set GH_TOKEN env var before starting to avoid being rate limited by GH.

I'll open the docs DB, and then add a README.

**Comment by gaborcsardi** [comment]
Also, instead of `bin/www`, you want to watch the files for changes, probably. E.g. the `supervisor` node package can do this:

```
npm install -g supervisor
PORT=3001 supervisor bin/www
```

You might need `sudo npm install ...` depending on your node setup.

**Comment by gaborcsardi** [comment]
OK, I opened the DB, so you should see the same on the local site. Will add a README in a sec.
