### ISSUE TITLE
github cran mirror out of sync with metacran and cran

### ISSUE THREAD

**Issue by Thell** [metacran/metacranweb#78]
3 Examples:

1. gridSVG
2. gmp
3. Rmpfr

I was going to take a look at the mirroring script, but can't find it in the ocean of repos. :)

**Comment by gaborcsardi** [comment]
Indeed.

I am rewriting the script, actually. New version will be here:
https://github.com/gaborcsardi/cranatgh

**Comment by Thell** [comment]
Gotcha, thanks. I'll watch that space.

**Comment by gaborcsardi** [comment]
Allright, updates seem to work fine now, so I can close this. They are triggered from https://github.com/metacran/cron/blob/27a15e8403c8898574eb808af0c2414868a5bf56/.openshift/cron/minutely/update-crandb.r and use the web app at https://github.com/metacran/cranatgh.app which in turn uses the Jenkins installation at http://jenkins.r-pkg.org:8080

The Jenkins installation is within Dokku, using this Dokku plugin: https://github.com/metacran/dokku-rocker-jenkins-cranatgh which uses this Docker image: https://github.com/metacran/rocker-jenkins

This is better than updating from openshift directly, because updates might take some time, and the cron script runs every minute. So it is better to put them in some kind of queue, like the Jenkins queue.
